Test-only PR
sindresorhus/refined-github pull request #4030
Opened 2021-02-27 20:02 UTC by fregante

For #4029

2021-02-27 20:03 UTC, fregante commented
Comment

2021-02-27 20:03 UTC, fregante commented
Hidden comment

2021-02-27 20:04 UTC, fregante commented on .gitignore
> +// MUCH IGNORE
Review comment

2021-02-27 20:04 UTC, fregante commented on .gitignore
>  node_modules
Resolved review comment

2021-02-27 20:04 UTC, fregante commented on .gitignore
> +// MUCH IGNORE
Resolved single review comment

2021-02-27 20:04 UTC, fregante reviewed
Review

2021-02-27 20:05 UTC, fregante reviewed
Review with comment and this comment

2021-02-27 20:05 UTC, fregante commented on .gitignore
>  yarn.lock
Comment part of a review

2021-02-27 20:06 UTC, fregante commented on .gitignore
>  distribution/build
Comment part of a review without main comment

2021-02-27 20:06 UTC, fregante commented on .gitignore
> +// MUCH IGNORE
Comment part of a whole review started later

2021-02-27 20:06 UTC, fregante commented on .gitignore
>  yarn.lock
Comment part of a whole review started later, but also resolved

2021-02-27 20:08 UTC, fregante commented on .gitignore
> +// VERY NOISE
Outdated comment

2021-02-27 20:14 UTC, fregante commented
dat's alot.

2021-02-27 20:35 UTC, fregante reviewed
Whole review, with comment in past, resolved review

2021-02-27 20:35 UTC, fregante commented on .gitignore
>  node_modules
Comment part of a whole review started later, but also resolved

2021-02-27 20:36 UTC, fregante commented
@yakov116 can you leave a no-comment Approve review? Reopen and close if necessary

2021-02-27 20:55 UTC, fregante commented on .gitignore
>  .parcel-cache
Resolved comment in unresolved review thread

2021-02-27 21:06 UTC, fregante commented on .gitignore
>  !test/web-ext-profile/.gitkeep
Review with multiple threads (thread 1)

2021-02-27 21:06 UTC, fregante commented on .gitignore
>  .cache
Review with multiple threads (thread 2)

2021-02-28 03:30 UTC, yakov116 requested changes
Test request changes

2021-02-28 03:30 UTC, yakov116 approved these changes

2021-02-28 03:30 UTC, yakov116 approved these changes
Appove with comment

2021-02-28 03:32 UTC, closed without merging

2022-06-04 08:56 UTC, fregante commented
Someone please delete this comment so we get the "Comment deleted" event