Consistent button label in `quick-repo-deletion`
sindresorhus/refined-github pull request #4331
Opened 2021-05-09 06:03 UTC by xnuk

Respecting: 0d186f70335f1efa2dfbe213f16dbcf7dff6e50e

## Test URLs
Check your any forked repositories.

## Screenshot
### Before
!['Delete fork' action button preceding the 'Watch', 'Star', and 'Fork' buttons.](https://user-images.githubusercontent.com/3071003/117562067-0992b980-b0d7-11eb-8c48-a05071b8d327.png)

### After
!['Delete repo' action button preceding the 'Watch', 'Star', and 'Fork' buttons.](https://user-images.githubusercontent.com/3071003/117562054-fc75ca80-b0d6-11eb-9d66-443f8a662de7.png)

2021-05-09 10:08 UTC, fregante commented
Thanks for the PR! https://github.com/sindresorhus/refined-github/commit/0d186f70335f1efa2dfbe213f16dbcf7dff6e50e was actually undone so the feature only appears on forks. I'd rather make it clear that the button deletes a fork, rather than a scary "delete repo"

2021-05-09 19:49 UTC, yakov116 requested changes
Don't see why we need a var, just change the text.

2021-05-09 19:49 UTC, yakov116 commented on source/features/quick-repo-deletion.tsx
> +		button.textContent = buttonText;
```suggestion
		button.textContent = 'Delete fork';
```

2021-05-09 19:49 UTC, yakov116 commented on source/features/quick-repo-deletion.tsx
> +	const buttonText = button.textContent;
```suggestion
```

2021-05-10 03:37 UTC, merged

2021-05-10 03:37 UTC, fregante commented
Thank you for the PR!