Rename `more-dropdown` to `more-dropdown-links`
sindresorhus/refined-github pull request #4584
Opened 2021-07-19 03:31 UTC by yakov116

Migration will happen in the other PR, after the feature is renamed.

2021-07-19 06:08 UTC, fregante approved these changes

2021-07-19 06:09 UTC, fregante commented
Unchecked but I assume it matches the previous code. Merge at will

2021-07-19 07:34 UTC, FloEdelmann requested changes

2021-07-19 07:34 UTC, FloEdelmann commented on readme.md
>  - [](# "more-dropdown") [Adds useful links to the repository navigation dropdown and moves the "Security" and "Insights" tabs to it as well.](https://user-images.githubusercontent.com/16872793/124681
This line should be dropped, right?

2021-07-19 07:34 UTC, FloEdelmann commented on source/features/remove-unused-repo-tabs.tsx
> +	// The user may have disabled `more-dropdown` so un-hide it
```suggestion
	// The user may have disabled `more-dropdown-links` so un-hide it
```

2021-07-19 10:19 UTC, merged

2021-12-11 23:57 UTC, kdcloverkid commented
more-dropdown-links