Feat: add the `always` variable to `features.add()`
sindresorhus/refined-github pull request #4800
Opened 2021-09-19 15:36 UTC by gamemaker1

## What this PR does

Adds the `required` variable from https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-812843149 as the `always` variable. Also move negative `exclude`s to their own list of `always` tests.

> https://github.com/sindresorhus/refined-github/blob/936eedbb0bb37a30fc44a2cc7e5f3af31f24a3fc/source/features/fork-source-link-same-view.tsx#L24-L32
> 
> Could be
> 
> ```js
> 	required: [ // name TBD
>		pageDetect.isForkedRepo
>	],
>	include: [
>		pageDetect.isSingleFile,
>		pageDetect.isRepoTree,
>		pageDetect.isEditingFile
>	],
>	exclude: [
>		pageDetect.isRepoRoot
>	],
>```
>
> Side note: https://github.com/sindresorhus/refined-github/pull/4797/files#r711719028

---

I will be changing all the instances of negative exclusions to their own list of `always` tests, until then, the PR will stay a draft. Please do review the changes I made to `source/features/index.ts` while adding the `always` test though.

2021-09-19 15:43 UTC, yakov116 commented
@gamemaker1 please lint before commiting thanks

2021-09-19 15:44 UTC, gamemaker1 commented
Sorry about that I usually don't use semicolons, so the linter keeps failing. Maybe I should set a pre-commit hook for that 😅

2021-09-19 15:53 UTC, yakov116 commented on source/features/useful-not-found-page.tsx
> +		showDefaultBranchLink(); showAlternateLink();
This should be put into a regular init function.

2021-09-19 15:53 UTC, yakov116 commented on source/features/useful-not-found-page.tsx
> +	always: [pageDetect.is404],
```suggestion
	always: [
		pageDetect.is404
	],
```

In all places

2021-09-19 16:31 UTC, cheap-glitch commented
Thanks for the PR! Imo `required` is clearer than `always`, so I'd prefer the first one. Just my opinion though.

2021-09-19 16:31 UTC, yakov116 commented on source/features/useful-not-found-page.tsx
> +	always: [pageDetect.is404],
> In all places

2021-09-19 16:42 UTC, gamemaker1 commented
> Thanks for the PR! Imo `required` is clearer than `always`, so I'd prefer the first one. Just my opinion though.

Ok, sure I'll change it to `required`.

2021-09-19 17:13 UTC, fregante commented
> Thanks for the PR! Imo `required` is clearer than `always`, so I'd prefer the first one. Just my opinion though.

Agreed, but is it clear that _every_ filter must be true? Is there anything better? In essence we have:

- every
- any – include 
- none – exclude

But I don't know if they make sense on their own

2021-09-19 17:15 UTC, fregante commented
Also keep in mind that we have a special handling of is404 in features/index.tsx, so make sure that's updated if necessary.

2021-09-19 17:16 UTC, yakov116 commented
> asLongAs

👍

2021-09-19 17:18 UTC, fregante commented on source/features/useful-not-found-page.tsx
> +	include: [() => parseCurrentURL().length > 1],
Since both are required

```suggestion
	always: [
		pageDetect.is404,
		() => parseCurrentURL().length > 1,
	],
```

2021-09-20 02:48 UTC, gamemaker1 commented
Changed `always` to `asLongAs`

2021-09-20 03:23 UTC, gamemaker1 commented
I think I got all of them, let me know if I missed any!

2021-09-20 06:20 UTC, fregante commented on source/features/index.tsx
> +	// If any asLongAs is false, every `include` is false or no `exclude` is true, don’t run the feature
```suggestion
	// Features are enabled if every `asLongAs` matches, at least one `include` matches, none of `exclude` matches
```

We just need to make sure that works as expected, we should probably extract this condition into a `shouldFeatureRun({include, exclude, asLongAs})` (in helpers.ts) and add tests for it.

2021-09-20 06:20 UTC, fregante commented on source/features/link-to-github-io.tsx
> +		() => getRepo()?.name.endsWith('.github.io') ?? false,
```suggestion
		() => Boolean(getRepo()?.name.endsWith('.github.io')),
```

2021-09-20 07:43 UTC, gamemaker1 commented
Added a couple of tests, let me know if and which more tests I should add.

2021-09-20 11:12 UTC, fregante commented
Let's move these defaults to the new helper function:

https://github.com/sindresorhus/refined-github/pull/4800/files#diff-cb1dafea7a9c68c5c2ebb2d56f749b3506c13f7d26feeaf56c86521b25c60358R222-R224

Once you remove the `= []` from there, I think you'll only need to fix the 404 check line a bit later, from `include.includes` to `include?.includes`

2021-09-21 06:48 UTC, gamemaker1 commented
Hmmm.. you can't specify a type and a default value in an object

2021-09-21 11:13 UTC, gamemaker1 commented
Yay, checks pass! Thanks @fregante!

Any more changes needed?

2021-09-21 11:22 UTC, fregante approved these changes

2021-09-23 03:29 UTC, yakov116 requested changes
LGTM

Please also add this to the contribution.md

2021-09-23 03:29 UTC, yakov116 commented on source/features/index.tsx
> +import {shouldFeatureRun} from '../github-helpers';
Should be moved up 2 lines

2021-09-23 03:31 UTC, gamemaker1 commented on source/features/index.tsx
> +import {shouldFeatureRun} from '../github-helpers';
Sure

2021-09-23 03:40 UTC, gamemaker1 commented
> Please also add this to the contributing.md

Done!

2021-09-24 13:53 UTC, yakov116 approved these changes
Untested but LGTM

2021-09-26 05:08 UTC, fregante commented
Thank you Vedant! It works!

2021-09-26 05:08 UTC, merged